blank_issues_enabled: false
contact_links:
  - name: WalkScape Index Discussions
    url: https://github.com/walkscape-index/walkscape-index/discussions
    about: Please ask questions or discuss features/ideas in GitHub Discussions.
